package com.nextlabs.utc.conf.hibernate;

// Generated May 9, 2013 1:12:51 PM by Hibernate Tools 3.4.0.CR1

/**
 * CountryMaster generated by hbm2java
 */
public class CountryMaster {

	String countryCode;
	public String getCountryCode() {
		return countryCode;
	}
	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}
	public String getShortName() {
		return shortName;
	}
	public void setShortName(String shortName) {
		this.shortName = shortName;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	String shortName;
	String name;

}
