package com.nextlabs.utc.conf.hibernate;

// Generated May 9, 2013 1:12:51 PM by Hibernate Tools 3.4.0.CR1

/**
 * IpcountryMapping generated by hbm2java
 */
public class IpcountryMapping {

	private int id;
	private String cdir;
	private String countryCode;
	private String type;

	public IpcountryMapping() {
	}

	public IpcountryMapping(int id) {
		this.id = id;
	}

	public IpcountryMapping(int id, String cdir,
			String countryCode, String type) {
		this.id = id;
		this.cdir = cdir;
		this.countryCode = countryCode;
		this.type = type;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCdir() {
		return this.cdir;
	}

	public void setCdir(String cdir) {
		this.cdir = cdir;
	}

	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
